### ISSUE TITLE
MAC Display Zoomed In

### ISSUE THREAD

**Issue by orravandaz** [daviderud/SDRPlusPlusUtils#1]
Sometimes the app opens in the normal display resolution but more times it opens in what would appear to be a zoomed in display. Everything still works but it's difficult to have the need to scroll left right and up down to get to all of the controls and features. Any solution to have the app always open in the correct display resolution? Sss screenshoots attached.
[screenshot-2.pdf](https://github.com/daviderud/SDRPlusPlusUtils/files/12667146/screenshot-2.pdf)

**Comment by daviderud** [comment]
hi this is not the repository of the SDRPlusPlus application, refer to here:
https://github.com/AlexandreRouma/SDRPlusPlus/issues
